import React, { useState } from 'react';
import {
  FileText,
  CheckCircle2,
  FileCheck,
  PhoneCall,
  ExternalLink,
  X,
  HelpCircle,
  Award,
  Sparkles
} from 'lucide-react';
import { Language, HealthScheme } from '../../types';
import { HEALTH_SCHEMES } from '../../data/mockData';
import { translations } from '../../data/translations';

interface GovernmentSchemesProps {
  language: Language;
}

export const GovernmentSchemes: React.FC<GovernmentSchemesProps> = ({ language }) => {
  const t = translations[language];
  const [selectedScheme, setSelectedScheme] = useState<HealthScheme | null>(null);

  const isHindi = language === 'hi';

  const fullSchemes: HealthScheme[] = [
    ...HEALTH_SCHEMES,
    {
      id: 'mission_indradhanush',
      nameEn: 'Intensified Mission Indradhanush (IMI)',
      nameHi: 'तीव्र मिशन इन्द्रधनुष अभियान',
      shortTagEn: 'Free Complete Child Vaccination',
      shortTagHi: 'बच्चों का सम्पूर्ण मुफ्त टीकाकरण',
      coverageEn: 'Full immunization coverage for pregnant women and children under 2 years against 12 vaccine-preventable diseases.',
      coverageHi: '2 वर्ष से कम आयु के बच्चों और गर्भवती महिलाओं का 12 जानलेवा बीमारियों से सम्पूर्ण मुफ्त टीकाकरण।',
      descriptionEn: 'Government drive ensuring no pregnant woman or infant misses life-saving vaccines even in remote rural villages.',
      descriptionHi: 'दूरदराज के ग्रामीण इलाकों में भी हर गर्भवती महिला और शिशु को सभी टीके समय पर उपलब्ध कराने का सरकारी अभियान।',
      eligibilityEn: ['Pregnant women and infants/children up to 2 years in rural areas'],
      eligibilityHi: ['ग्रामीण क्षेत्रों की सभी गर्भवती महिलाएं तथा 2 वर्ष तक के शिशु'],
      benefitsEn: [
        '100% Free vaccines given at Anganwadi / Sub-Centre doorstep sessions',
        'Mother & Child Protection (MCP) Card tracking and SMS reminders',
        'Vitamin A liquid doses and Deworming tablets provided free'
      ],
      benefitsHi: [
        'आंगनबाड़ी व स्वास्थ्य उपकेंद्र पर 100% मुफ्त टीकाकरण',
        'मातृ एवं शिशु सुरक्षा (MCP) कार्ड और एसएमएस (SMS) रिमाइंडर',
        'विटामिन ए और पेट के कीड़े की दवाएं मुफ्त'
      ],
      documentsEn: ['Aadhaar Card of mother', 'MCP Card (Mamta / Anganwadi Card)'],
      documentsHi: ['मां का आधार कार्ड', 'मातृ एवं शिशु सुरक्षा (MCP) कार्ड'],
      howToApplyStepsEn: [
        'Contact your village ASHA worker or Anganwadi worker.',
        'Bring child to monthly Village Health Sanitation & Nutrition Day (VHSND) session.',
        'Get vaccinations recorded in MCP Card.'
      ],
      howToApplyStepsHi: [
        'अपनी ग्राम आशा बहू या आंगनबाड़ी कार्यकत्री से संपर्क करें।',
        'मासिक ग्राम स्वास्थ्य पोषण दिवस (VHSND/सत्र) पर बच्चे को लाएं।',
        'एमसीपी कार्ड में टीका लगवाकर दर्ज कराएं।'
      ],
      helpline: '1800-180-1104',
      portalUrl: 'https://mohfw.gov.in'
    },
    {
      id: 'nikshay_poshan',
      nameEn: 'Nikshay Poshan Yojana (TB Relief Scheme)',
      nameHi: 'निक्षय पोषण योजना (टीबी मरीज सहायता)',
      shortTagEn: '₹1,000 / Month Diet Support',
      shortTagHi: '₹1,000 प्रति माह पोषण राशि',
      coverageEn: '₹1,000 monthly direct bank transfer to all active TB patients for nutritious food during treatment.',
      coverageHi: 'इलाज जारी रहने तक सभी टीबी मरीजों को पौष्टिक आहार हेतु ₹1,000 प्रति माह सीधे खाते में।',
      descriptionEn: 'Financial assistance scheme by MoHFW to ensure adequate nutrition during anti-TB treatment.',
      descriptionHi: 'टीबी के इलाज के दौरान मरीज के खान-पान और पोषण सुधार हेतु सरकारी वित्तीय सहायता योजना।',
      eligibilityEn: ['All notified TB patients undergoing treatment in government or private healthcare'],
      eligibilityHi: ['सरकारी या निजी अस्पताल में इलाज करा रहे सभी पंजीकृत टीबी मरीज'],
      benefitsEn: [
        '₹1,000 per month directly deposited to patient bank account via DBT',
        'Free 6-month DOTS anti-TB medication and blood tests'
      ],
      benefitsHi: [
        'डीबीटी के माध्यम से मरीज के बैंक खाते में ₹1,000 प्रति माह',
        'टीबी की 6 महीने की दवाएं (DOTS) और जांच 100% मुफ्त'
      ],
      documentsEn: ['Aadhaar Card', 'Patient Bank Passbook', 'Nikshay ID generated by PHC'],
      documentsHi: ['आधार कार्ड', 'मरीज की बैंक पासबुक', 'पीएचसी द्वारा जारी निक्षय आईडी'],
      howToApplyStepsEn: [
        'Get tested for TB at nearest PHC and obtain your Nikshay ID.',
        'Submit Aadhaar and Bank Passbook copy to PHC TB Officer.',
        'Monthly payment automatically transfers until treatment completion.'
      ],
      howToApplyStepsHi: [
        'पीएचसी में बलगम जांच कराकर अपनी निक्षय आईडी बनवाएं।',
        'आधार और बैंक पासबुक की कॉपी जमा करें।',
        'इलाज पूरा होने तक हर महीने नकद राशि सीधे खाते में पाएं।'
      ],
      helpline: '1800-11-6666',
      portalUrl: 'https://nikshay.in'
    }
  ];

  return (
    <div className="space-y-6 pb-12">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-emerald-800 to-[#028090] text-white rounded-2xl p-6 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#02C39A] text-[#0B3B3C] font-extrabold text-xs uppercase tracking-wide">
            <FileText className="h-4 w-4" />
            {language === 'hi' ? 'मॉड्यूल 5' : 'Module 5'}
          </div>
          <h2 className="text-2xl font-extrabold text-white">
            {t.modSchemesTitle}
          </h2>
          <p className="text-xs sm:text-sm text-emerald-100 font-medium">
            {t.modSchemesDesc}
          </p>
        </div>

        <div className="bg-white/10 backdrop-blur-xs p-3 rounded-2xl border border-white/20 text-center shrink-0">
          <div className="text-xl font-extrabold text-[#02C39A]">100% Govt Funded</div>
          <div className="text-[11px] font-bold text-emerald-100">
            {isHindi ? 'मुफ्त कार्ड व नकद सहायता' : 'Free Cards & Cash Aid'}
          </div>
        </div>
      </div>

      {/* Schemes Grid Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {fullSchemes.map(sch => {
          const name = isHindi ? sch.nameHi : sch.nameEn;
          const tag = isHindi ? sch.shortTagHi : sch.shortTagEn;
          const desc = isHindi ? sch.descriptionHi : sch.descriptionEn;
          const benefits = isHindi ? sch.benefitsHi : sch.benefitsEn;
          const docs = isHindi ? sch.documentsHi : sch.documentsEn;

          return (
            <div
              key={sch.id}
              className="bg-white rounded-2xl border border-teal-100 p-5 shadow-xs space-y-4 flex flex-col justify-between hover:shadow-md transition-all"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-extrabold px-3 py-1 rounded-full bg-emerald-50 text-emerald-800 border border-emerald-200">
                    <Sparkles className="h-3 w-3 inline mr-1 text-emerald-600" />
                    {tag}
                  </span>
                  <span className="text-xs font-bold text-slate-500">
                    📞 {sch.helpline}
                  </span>
                </div>

                <h3 className="font-extrabold text-slate-900 text-lg leading-snug">
                  {name}
                </h3>

                <p className="text-xs text-slate-600 font-medium leading-relaxed">
                  {desc}
                </p>

                {/* Key Benefits List */}
                <div className="bg-emerald-50/70 border border-emerald-200/80 rounded-xl p-3 space-y-1">
                  <h4 className="text-xs font-bold text-emerald-900 uppercase tracking-wider">
                    {t.benefits}:
                  </h4>
                  <ul className="text-xs text-emerald-950 space-y-1 font-medium">
                    {benefits.map((b, i) => (
                      <li key={i} className="flex items-start gap-1.5">
                        <span className="text-emerald-600 font-bold">✓</span>
                        <span>{b}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              <div className="pt-3 border-t border-slate-100 flex items-center gap-2">
                <button
                  onClick={() => setSelectedScheme(sch)}
                  className="w-full inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-[#028090] hover:bg-[#00A896] text-white font-extrabold text-xs transition-all shadow-xs"
                >
                  <Award className="h-4 w-4 text-[#02C39A]" />
                  {t.howToApply}
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* HOW TO APPLY MODAL */}
      {selectedScheme && (
        <div className="fixed inset-0 bg-slate-900/80 backdrop-blur-xs z-50 flex items-center justify-center p-3 sm:p-6">
          <div className="bg-white rounded-3xl max-w-xl w-full p-6 shadow-2xl border border-teal-200 space-y-5 relative animate-in fade-in zoom-in duration-200 max-h-[90vh] overflow-y-auto">
            <div className="flex items-start justify-between border-b pb-3">
              <div>
                <span className="text-[10px] font-extrabold uppercase px-2 py-0.5 rounded-md bg-emerald-50 text-emerald-800 border border-emerald-200">
                  {isHindi ? selectedScheme.shortTagHi : selectedScheme.shortTagEn}
                </span>
                <h3 className="text-lg font-extrabold text-slate-900 mt-1">
                  {isHindi ? selectedScheme.nameHi : selectedScheme.nameEn}
                </h3>
              </div>
              <button
                onClick={() => setSelectedScheme(null)}
                className="h-8 w-8 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-600 flex items-center justify-center"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="space-y-4 text-xs sm:text-sm">
              {/* Eligibility */}
              <div className="space-y-1.5">
                <h4 className="font-extrabold text-slate-800 uppercase tracking-wider text-xs">
                  {t.eligibility}:
                </h4>
                <ul className="bg-slate-50 p-3 rounded-xl border border-slate-200/80 space-y-1 font-medium text-slate-700">
                  {(isHindi ? selectedScheme.eligibilityHi : selectedScheme.eligibilityEn).map((e, idx) => (
                    <li key={idx} className="flex items-start gap-1.5">
                      <span className="text-[#028090] font-bold">•</span>
                      <span>{e}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Required Docs */}
              <div className="space-y-1.5">
                <h4 className="font-extrabold text-slate-800 uppercase tracking-wider text-xs flex items-center gap-1.5">
                  <FileCheck className="h-4 w-4 text-teal-600" />
                  {t.requiredDocs}:
                </h4>
                <div className="flex flex-wrap gap-2">
                  {(isHindi ? selectedScheme.documentsHi : selectedScheme.documentsEn).map((doc, idx) => (
                    <span key={idx} className="bg-teal-50 text-[#028090] px-3 py-1.5 rounded-lg border border-teal-200 font-bold text-xs">
                      📄 {doc}
                    </span>
                  ))}
                </div>
              </div>

              {/* How to Apply Steps */}
              <div className="space-y-1.5">
                <h4 className="font-extrabold text-slate-800 uppercase tracking-wider text-xs">
                  {isHindi ? 'आवेदन करने की आसान प्रक्रिया:' : 'Step-by-Step Application Process:'}
                </h4>
                <div className="space-y-2">
                  {(isHindi ? selectedScheme.howToApplyStepsHi : selectedScheme.howToApplyStepsEn).map((step, idx) => (
                    <div key={idx} className="flex items-start gap-3 bg-emerald-50/60 p-3 rounded-xl border border-emerald-200/80">
                      <span className="h-6 w-6 rounded-lg bg-emerald-600 text-white font-bold flex items-center justify-center text-xs shrink-0">
                        {idx + 1}
                      </span>
                      <p className="text-emerald-950 font-medium text-xs sm:text-sm">
                        {step}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Helpline Phone */}
              <div className="bg-slate-900 text-white p-3.5 rounded-xl flex items-center justify-between">
                <div>
                  <div className="text-xs text-slate-400 font-medium">{isHindi ? 'टोल-फ्री हेल्पलाइन नंबर:' : 'Toll-Free Helpline:'}</div>
                  <div className="text-base font-extrabold text-[#02C39A]">{selectedScheme.helpline}</div>
                </div>
                <a
                  href={`tel:${selectedScheme.helpline.split('/')[0].trim()}`}
                  className="px-3.5 py-2 rounded-lg bg-[#028090] hover:bg-[#00A896] text-white font-bold text-xs flex items-center gap-1.5"
                >
                  <PhoneCall className="h-4 w-4" />
                  {t.callNow}
                </a>
              </div>
            </div>

            <div className="pt-2">
              <button
                onClick={() => setSelectedScheme(null)}
                className="w-full py-2.5 rounded-xl border border-slate-300 text-slate-700 font-bold text-xs hover:bg-slate-50"
              >
                {t.closeModal}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
